- .github/workflows/main.yml
- .github/workflows/remove-needs-qa.yml
- README.md
> All references to master now refer to main

- README.md
- lib/memo_wise.rb
See old PR conversation here: #25 
> Change internal data structure to nested hash

- Gemfile
- Gemfile.lock
- spec/memo_wise_spec.rb
> Add test with Values gem

- README.md
- lib/memo_wise.rb
> Add YARD doc links between README.md and MemoWise

- README.md
> Clarify in README when benchmarks are run

- .github/workflows/main.yml
- README.md
> Only run github actions on PRs and pushes to main

- README.md
- memo_wise.gemspec
**THIS IS NOT YET READY TO MERGE! SEE CHECKLIST IN #37**
Closes #37
> Minor README polish

- CHANGELOG.md
This adds a changelog and details noteable changes. I also added tags to correspond to this changelog.
Resolves #43
> Added a changelog and tags according to keepachangelog.com

- .github/PULL_REQUEST_TEMPLATE.md
Ensures we're adding lines to the changelog when we're making changes
> Add changelog to PR template

- CHANGELOG.md
- README.md
Added logo licensing and credit to README, added logo as an item to CHANGELOG
> Added Logo section in README.md with license

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- memo_wise.gemspec
Add Rakefile with "bundler/gem_tasks"
Add instructions for releasing to README.md
Add authors and emails to gemspec
> Prepare for initial gem release

- CHANGELOG.md
- README.md
- lib/memo_wise.rb
> Document confusing module test behavior

- README.md
- benchmarks/Gemfile
- benchmarks/Gemfile.lock
- benchmarks/benchmarks.rb
- spec/memo_wise_spec.rb
- spec/support/define_methods_for_testing_memo_wise.rb
> Add test and benchmarks for one arg, optional args

- CHANGELOG.md
- README.md
- lib/memo_wise.rb
> Reduce fetch key array allocations where possible

- README.md
- ~[ ] Copy the latest benchmark results into the `README.md` and update this PR~
- ~[ ] If this change merits an update to `CHANGELOG.md`, add an entry following Keep a Changelog [guidelines](https://keepachangelog.com/en/1.0.0/) with [semantic versioning](https://semver.org/)~
**Reviewers, please:**
> Make benchmarks more readable in README

- .dokaz
- .github/workflows/main.yml
- Gemfile
- Gemfile.lock
- README.md
- lib/memo_wise.rb
- spec/dokaz_helpers.rb
* Expand docs for class-level .preset_memo_wise
* Expand docs for class-level .reset_memo_wise
* Add dokaz gem and configure to run code in README.md
> Add full documentation for class methods

- lib/memo_wise.rb
- lib/memo_wise/internal_api.rb
Extract common code:
* original_memo_wised_name
* target_class [ target.instance_of?(Class) ? ... ]
- ~Copy the latest benchmark results into the `README.md` and update this PR~
- ~If this change merits an update to `CHANGELOG.md`, add an entry following Keep a Changelog [guidelines](https://keepachangelog.com/en/1.0.0/) with [semantic versioning](https://semver.org/)~
> Refactor to DRY internal api code

- CHANGELOG.md
> Update CHANGELOG.md for 1.0.0

- Gemfile.lock
- lib/memo_wise/version.rb
> Bump version to 1.0.0

- .rubocop.yml
- CHANGELOG.md
- README.md
- benchmarks/benchmarks.rb
- lib/memo_wise.rb
- lib/memo_wise/internal_api.rb
- spec/preset_memo_wise_spec.rb
- spec/reset_memo_wise_spec.rb
- spec/support/define_methods_for_testing_memo_wise.rb
> Add further optimizations

- CHANGELOG.md
> Update CHANGELOG.md for V1.1.0

- README.md
> Update readme with blog posts

- Gemfile.lock
- lib/memo_wise/version.rb
> Bump version to V1.1.0

- README.md
> Add esoteric ruby in memowise post to readme

- README.md
- benchmarks/benchmarks.rb
> Sort benchmarks headers to match cells

- spec/spec_helper.rb
> Randomize RSpec test ordering

- CHANGELOG.md
- README.md
- lib/memo_wise.rb
- lib/memo_wise/internal_api.rb
- spec/support/define_methods_for_testing_memo_wise.rb
> Simplify data structures

- README.md
> Document memoization privacy in README.md

- CHANGELOG.md
- Gemfile.lock
- lib/memo_wise/version.rb
> Release version 1.2.0

- CHANGELOG.md
- README.md
> Add RubyConf links to README and fix CHANGELOG links

- spec/spec_helper.rb
- spec/support/check_repeatedly.rb
- spec/thread_safety_spec.rb
> Add spec of thread-safety accessing zero-arg method

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/memo_wise/version.rb
> Version 1.3.0

- CHANGELOG.md
- README.md
> Update CHANGELOG.md for v1.4.0

- Gemfile.lock
- lib/memo_wise/version.rb
> Bump version to v1.4.0

- spec/thread_safety_spec.rb
> Add thread-safety tests for 0-, 1-, and 2-arity methods

- Gemfile.lock
- lib/memo_wise/version.rb
> Bump version to v1.5.0

- lib/memo_wise.rb
- spec/memo_wise_spec.rb
> Fix memoization with inheritance

- Gemfile.lock
- lib/memo_wise/version.rb
> Bump version to 1.6.0

- benchmarks/Gemfile
- benchmarks/benchmarks.rb
This PR allows us to more easily benchmark against the version of MemoWise on the main branch in GitHub. In the GitHub actions to print benchmarks, we now also print benchmarks of running the MemoWise main branch against whatever branch a PR creates. This creates an easier way to see if a change is actually more performant for both local development and PR review.
> Nuanced benchmarking

- CHANGELOG.md
> Update CHANGELOG.md for 1.7.0

- CHANGELOG.md
- README.md
Closes #242
**Some things I would love reviewer input on:**
- Overall structure. I thought "Gem enhancements" and "Project enhancements" made sense but I'm open to any and all feedback.
- Tenses. I went back and forth so many times on "added" vs. "add" vs. "has been added" etc.
- Breaking changes. I think it's helpful to show them, but realistically we only have one entry so I wasn't sure if there was a better/more minimal way to list them (I tried putting it within the `Gem enhancements:` section and a few other alternatives and don't love any of them).
- PR links. They're nice but I didn't want to go back and add them all so I just removed the few we had. 🤷‍♀️ 
> Restructure CHANGELOG.md for clarity and consistency

- CHANGELOG.md
> Add changelog improvements to changelog

- README.md
See docs: https://docs.codecov.com/docs/status-badges
> Fix Codecov badge and link in README.md

- Gemfile.lock
- lib/memo_wise/version.rb
> Bump version to 1.8.0

- README.md
> Update benchmark-ips version in README.md to match benchmarks

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/memo_wise/version.rb
> Bump version to v1.12.0
