lib/memo_wise.rb, spec/memo_wise_spec.rb
This PR defines `MemoWise#memo_wise` to memoize methods and `MemoWise#reset_memo_wise` to undo that memoization of methods.
=> Define #memo_wise and #reset_memo_wise

.travis.yml
We are using Github Actions for CI, not Travis.
Fixes #9
=> Remove unused Travis CI config

lib/memo_wise.rb, spec/memo_wise_spec.rb
This PR implements resetting of memoization. Once a method has already been memoized, it allows us to reset any memoized values while still leaving the method itself memoized.
Outside of the scope of this PR (but to come in later PR)
- YARDocs to describe this method
=> Implements #reset_memo_wise

README.md, benchmarks/Gemfile, lib/memo_wise.rb
Going to wait for benchmarking to merge before making claims on hard numbers here, but checking out the `first-benchmarks` branch, it looks like this doesn't have a negative effect on any methods with arguments, and speeds up the no args case to only ~2x the best gem we're comparing against.
=> Optimization for methods with no arguments

lib/memo_wise.rb, spec/memo_wise_spec.rb
This commit provides the ability to pass arguments to reset_memo_wise
Thanks to @jsartin513 for pairing!
=> Allow passing arguments to reset_memo_wise

README.md, benchmarks/benchmarks.rb
This commit changes the benchmarks to solely test memoized
value retrieval. All other costs (instance initialization,
memoized value storage) are removed from benchmarking to
limit ourselves to just what we care about optimizing the
most.
=> Reduce potential noise from benchmarks

README.md, benchmarks/benchmarks.rb, lib/memo_wise.rb, spec/memo_wise_spec.rb
This commit separates *args from **kwargs in the memo_wise'd
method signatures, and only uses the minimum necessary. This
allows us to gain performance benefits (fewer allocations in
many cases) and silence the Ruby warnings.
=> Separate *args from **kwargs

Gemfile
We only run linters in CI on Ruby 2.7, and the dependencies
of the panolint gem have broken (hopefully temporarily) on
JRuby now.
We'd like to match our CI build dependencies up with the tests
that we run, so that we don't get test failures from dependency
incompatibilities with Ruby versions that we won't be running them
on.
=> Install gem panolint only on Ruby 2.7

README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
Implements #preset_memo_wise with an API that has instance.preset_memo_wise(method_name, *args) { value }
To come in future PRs:
- Validate params sent to #preset_memo_wise
- YARDocs for #preset_memo_wise
=> Preset memo wise

.github/workflows/main.yml, .yardopts, Gemfile, Gemfile.lock, README.md
Run 'bundle exec yard server' to run a local server to
iterate on documentation and see the results in a browser.
=> Generate YARD docs locally

.github/workflows/main.yml, memo_wise.gemspec
This closes #40 to decide on earliest Ruby support by adding tests for Ruby 2.4
=> Adding Ruby 2.4 Support

.github/workflows/main.yml, .yardopts, Gemfile, Gemfile.lock, README.md, benchmarks/Gemfile, lib/memo_wise.rb, spec/doctest_helper.rb, spec/memo_wise_spec.rb
First pass through the MemoWise module. Includes all of the non-metaprogrammed class and instance methods. Excludes all of the meta-programmed methods, which will come in a separate PR after we figure out the best way to document them.
We add examples in the YARD doc comments which are tested using the
`yard doctest` plugin.
=> Backfill initial yard docs

README.md, lib/memo_wise.rb
This PR uses the YARD `@!method` tag to document the class method that is created in `.prepended` -- the actual `.memo_wise` method!
=> Backfill metaprogrammed methods YARD docs

README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb, spec/spec_helper.rb
This PR:
* Adds CodeCov badge
* Adds `lib/memo_wise.rb` to the files evaluated by CodeCov
* Fixes private / protected memoization to improve CodeCov results
* Fails the test suite when line coverage lowers, or branch coverage falls below 90%
Resolves Issue #59
=> Add CodeCov badge and minimum coverages

.dependabot/config.yml
Fixes #22
Tested this with the online YAML parser linked from #22.
**After merging:**
=> Fix configuration for Dependabot v1

spec/memo_wise_spec.rb, spec/spec_helper.rb
Adds specs to ensure we're at 100% code coverage, and mandates 100% branch coverage moving forward.
Resolves #56
=> 100% code coverage

README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
This PR:
* Raises an `ArgumentError` when memoizing methods which have explicit block parameters
* Adds specs confirming we can't memoize methods with explicit or implicit block params
* Adds spec confirming we _can_ memoize methods with named proc params
* Adds documentation around memoizing methods with block params
Resolves #39.
=> Raise error when memoizing methods with block args

CHANGELOG.md, README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
Included in this PR is support for memoization of class methods,
which in Ruby are technically instance methods of the singleton
class.
Support class methods defined in two ways.
(1) The "self." syntax:
class SelfDot
prepend MemoWise
def self.foo; end
memo_wise self: :foo
end
(2) The "class << self" syntax:
class ClassShiftSelf
class << self
prepend MemoWise
def foo; end
memo_wise :foo
end
end
Resolves #35 
=> Add support for Class method memoization

CHANGELOG.md, README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
=> Support allocated instances

README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
This PR no longer raises an error when methods which take explicit block args are memoized. 
=> Removes raising error when memoizing methods which take block args

lib/memo_wise.rb, spec/memo_wise_spec.rb
=> Fix reset_memo_wise support for private methods

.gitignore, Gemfile.lock, benchmarks/Gemfile.lock, lib/memo_wise/version.rb
I'll also rebase this one after the previous two PRs are merged.
This is the archetypal final PR before running `rake release`, which does nothing other than officially bumping the version number.
In case you are wondering "when do we create a git tag?", actually the rake task will do that for us.
=> Bump version to 0.3.0

Gemfile, Gemfile.lock
Add 'branch: main' to Gemfile for the gem panolint, and run
'bundle update panolint'.
See #119
=> Fix dependabot errors due to panolint branch name

CHANGELOG.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
Currently on ruby 3.0, prepending MemoWise into a class which accepts keyword arguments
in its initializer causes an ArgumentError to be thrown:
ArgumentError (wrong number of arguments (given 1, expected 0; required keyword: :kwarg))
This change allows both positional and keyword arguments to initializers in classes which
use MemoWise.  This is compatible with versions before 3.0 as well.
=> Allow keyword arguments in initializers when including MemoWise

spec/memo_wise_spec.rb, spec/spec_helper.rb, spec/support/define_methods_for_testing_memo_wise.rb
Closes #129
More steps:
* Refactor specs: use comments to break up sections of specs
* Refactor specs: move instance method tests into contexts
* Refactor specs: extract shared examples for #memo_wise
* Extract definition of instance methods for testing
* Extract to a support file: definition of methods for testing
* Fix common test setup among instance/class/class-scope contexts
* Run shared examples for class << self context
* Simplify test method setup by reusing instance for class << self
=> Refactor specs to share setup among instance + class contexts

CHANGELOG.md, README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
As pointed out by @honigc in #137, the use of a default proc in the
core MemoWise Hash instance makes serialization using Marshal impossible.
This PR replaces the implementation with a simple Hash, and sets the
default values along the API code paths that previously relied on the
default value.
We cover the case in #reset_memo_wise where specific args are passed,
to avoid regression of a Nil error when attempting to reset args that
are not yet memoized, as this error would become possible now that
there is no default value proc in the Hash.
Closes #137
=> Fix Marshal serialization

lib/memo_wise.rb, spec/memo_wise_spec.rb
Steps:
* Refactor specs to extract shared examples
* Add class-level specs for .preset_memo_wise
* Implement class-level .preset_memp_wise
Closes #86
=> Add class method for preset memo wise

CHANGELOG.md, lib/memo_wise.rb, memo_wise.gemspec, spec/memo_wise_spec.rb
Steps:
* Refactor specs to extract shared examples for reset_memo_wise
* Add class 'self.' specs for .reset_memo_wise
* Add 'class << self' specs for .reset_memo_wise
* Implement class-level .reset_memo_wise
~- [ ] Copy the latest benchmark results into the `README.md` and update this PR~
=> Add class method for reset_memo_wise

.github/dependabot.yml
This helps us keep our github actions module versions up to
date over time.
=> Add dependabot for Github Actions to dependabot.yml

.github/workflows/main.yml, README.md
It is advised to use the 'bundler-cache: true' option
of the ruby/setup-ruby github instead of the actions/cache action:
* https://github.com/ruby/setup-ruby#bundle-config
In this configuration, in order to set bundler config, it
is advised to set BUNDLE_* environment variables before the
ruby/setup-ruby action runs:
* https://github.com/ruby/setup-ruby#bundle-config
To enable conditional setting of these environment variables, it
is advised to append to the $GITHUB_ENV file rather than using the
'env:' yaml section:
* https://github.community/t/possible-to-use-conditional-in-the-env-section-of-a-job/135170
=> Use caching from ruby/setup-ruby github action

spec/spec_helper.rb
Configure SimpleCov to ignore the specs directory.
=> Exclude 'specs' path from coverage

lib/memo_wise.rb, spec/proxying_original_method_params_spec.rb
In Panorama spec helper code 'initialized_double', we observed
that MemoWise interrupts the use of Ruby reflection on method
parameters, by replacing with delegating methods that have overly
generic signatures, like:
def initialize(...)
def slow_method(*arg, **kwargs)
After investigation, we had determined that it was not worth
the complexity cost, and potential fragility, to pursue a solution
where we re-create the original method parmeter signatures for our
delegating implementations.
This PR is a minimalistic alternative, which narrowly overrides only
the implementation of {Module#instance_method} so that, in the case
of either #initialize or a method that has had .memo_wise called on it,
we look up the original method and proxy the original result value of
calling …
=> Decorate .instance_method to proxy original params

lib/memo_wise.rb
Oops, it wasn't accurate to suggest that 'memo_wise' generates
method signatures that include '&block'.
=> Fix comment by removing inaccurate '&block'

lib/memo_wise.rb
Oops, looks like this was missed when we extracted the method
`MemoWise::InternalAPI.orginal_memo_wised_name`
=> Fix TODO: use extracted original_memo_wised_name

README.md, benchmarks/Gemfile, benchmarks/Gemfile.lock, benchmarks/benchmarks.rb
Congratulations on the MemoWise 1.0 release!
This PR adds benchmarks for `ddmemoize`, a memoization gem I wrote, and apparently also the slowest of them all. Oh no!
I had to adjust the memoization-activation code in the benchmarks a little, as DDMemoize activates itself using `DDMemoize.activate(self)` — a little unconventional, but I’m not a fan of include/extend/prepend metaprogramming as it’s a little too magic.
DDMemoize does bring some new stuff to the table: [memoization metrics (hit/miss ratio)](https://github.com/ddfreyne/ddmemoize#metrics) as well as soft references, which helps with memory pressure. (Though they both don’t quite help with performance, I imagine.)
=> Add ddmemoize benchmarks

benchmarks/Gemfile, benchmarks/benchmarks.rb
Added the Memoizable module from [dry-core](https://github.com/dry-rb/dry-core) to the benchmark. The 0 and 1 argument benchmarks favour `memo_wise`, while `dry-core` is faster in the others.
I'm not exactly sure what the differences in implementation are. Maybe there is more optimization potential here, or maybe it is simply a matter of prioritizing a certain type of methods.
The table in README.md seems to assume that other gems always run slower, therefore I wasn't sure how to update it. Should the table be restructured somehow or should I calculate the numbers manually? (memo_wise 2x slower => dry-core 0.5x slower)
=> Add dry-core Memoizable to the benchmark

.github/PULL_REQUEST_TEMPLATE.md, README.md, benchmarks/benchmarks.rb
This PR changes the benchmarks to use the json blob that [benchmark-ips](https://github.com/evanphx/benchmark-ips) exposes to print the benchmarks at the end so we can copy / paste that table for the README
=> Print table for benchmarks

spec/support/shared_context_for_class_methods_via_class_scope.rb, spec/support/shared_context_for_module_methods_via_class_scope.rb
Fixes #202
NOTE: I'm not sure if this is a good idea but it does make our tests much faster.
=> Speed up tests by reusing temporary classes/modules

CHANGELOG.md, lib/memo_wise.rb
=> Use obscure local variable names to avoid name collisions with arguments

CHANGELOG.md, README.md, lib/memo_wise.rb, spec/thread_safety_spec.rb
This updates the sentinel after updating the cache, and check the sentinel before checking the cache.  Otherwise, if there are two concurrent calls for an uncached value in separate threads, a thread-safety issue is possible:
1. Thread 1 sets sentinel value to true
2. Thread 2 gets cached value (nil is not set)
3. Thread 2 checks sentinel value (is true)
4. Thread 2 returns nil instead of correct value
5. Thread 1 sets cached value
This changes the behavior so that in the case of concurrent calls for an uncached value, the original method is called twice instead of in invalid value being returned.
This change may negatively affect performance for cached calls, I haven't benchmarked or tested this.
I'll leave the before merging changes to the maintainers if they choose …
=> Fix thread-safety for concurrent uncached calls

CHANGELOG.md, README.md, lib/memo_wise.rb, lib/memo_wise/internal_api.rb, spec/adding_methods_spec.rb, spec/memo_wise_spec.rb, spec/preset_memo_wise_spec.rb, spec/reset_memo_wise_spec.rb
This commit fixes a variety of bugs that occurred when a
parent class uses `MemoWise` and a child class inherits
from it and tries to use the memoized methods.
Fixes #228
=> Fix a variety of inheritance bugs

benchmarks/benchmarks.rb, lib/memo_wise.rb, spec/support/define_methods_for_testing_memo_wise.rb
This commit also changes the heredoc closing
signifier to `HEREDOC` everywhere, for clarity.
Closes #232
=> Switch heredocs from <<- to <<~

README.md, spec/thread_safety_spec.rb
When two threads concurrently call a zero-arg method which is in
the unmemoized state, they can return two different results.
For example, this could occur if we are memoizing:
* database query result
* filesystem read
* current time
* a random number
This PR adds documentation that this is expected behavior to README.md,
as well as a probabilistic spec that demonstrates the behavior.
=> Fix concurrent memoization of zero-arg methods multiple values

CHANGELOG.md, README.md, lib/memo_wise.rb, lib/memo_wise/internal_api.rb, spec/memo_wise/internal_api_spec.rb, spec/memo_wise_spec.rb, spec/support/shared_context_for_class_methods_via_class_scope.rb, spec/support/shared_context_for_module_methods_via_class_scope.rb, spec/thread_safety_spec.rb
This commit fixes several bugs related to inheritance by
delaying the calculation of the index used to store memoized
method results until the method itself is called. This incurs
a slight performance penalty the first time a method is called.
Closes #238
Closes #239
=> Fix multiple inheritance-related bugs

CHANGELOG.md, README.md, benchmarks/benchmarks.rb, lib/memo_wise.rb, lib/memo_wise/internal_api.rb, spec/preset_memo_wise_spec.rb, spec/support/check_repeatedly.rb, spec/thread_safety_spec.rb
Previous versions of `MemoWise` used an array as the
internal cache data structure, where each memoized method
uses a unique array index. However, complex inheritance
structures make it easy to have multiple methods accidentally
share the same array index on the same object, resulting
in nondeterministic and incorrect behavior.
While we may explore that optimization again in the future,
for the time being we are switching to a hash data structure
keyed on method name, which is safer because two methods
cannot share the same name in Ruby.
Fixes #251 
=> Revert internal data structure to simple hash

CHANGELOG.md, README.md, benchmarks/benchmarks.rb, lib/memo_wise.rb, spec/thread_safety_spec.rb
This commit fixes race conditions found in memoized methods
that take arguments. This comes at a slight performance cost
for truthy memoized values (due to switching from `Hash#[]`
to the slightly slower `Hash#fetch`) but will be faster when
memoized values are falsey.
This change removes the "truthy optimization" leading to these
race conditions and as a result allows us to simplify our
benchmark code as we no longer need to benchmark truthy and
falsey values separately.
=> Fix race conditions in methods with arguments

LICENSE.txt
Annual year change PR to adjust references to the current year.
At this time, the only change is in the MIT License file (c) line,
in LICENSE.txt
Let's merge on Jan 1 2022 to celebrate the New Year!
=> Change year to 2022

.github/workflows/main.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
The codecov gem has been [deprecated], and since Feb 1 2022 it
[errors] in CI.
This PR carries out the recommended [migration] steps to generate
XML using the simplecov-cobertura gem, and them add the Github Action
[uploader] to send that data to Codecov
[deprecated]: https://github.com/codecov/codecov-ruby
[errors]: https://github.com/panorama-ed/memo_wise/runs/5394171013?check_suite_focus=true
[migration]: https://docs.codecov.com/docs/deprecated-uploader-migration-guide#ruby-uploader
[uploader]: https://github.com/marketplace/actions/codecov
=> Fix Codecov uploader

README.md
InchCI has been down for many months. Let's remove the dead badge until
such time as this service is back, and we decide it's still valuable.
According to the Wayback Machine, it looks like inch-ci.org hasa been down
[since Nov 10, 2021](https://web.archive.org/web/20211110040521/https://inch-ci.org/) at least.
=> Remove broken InchCI badge from README.md

CHANGELOG.md, README.md, lib/memo_wise.rb, lib/memo_wise/internal_api.rb, spec/reset_memo_wise_spec.rb
This commit optimizes methods with multiple required arguments to use
nested hashes to store the memoized value (so each argument accesses
the next layer in the hash) rather than a single-layer hash with an
array key.
This is more performant because multiple `#hash` calls on simpler
data structures are faster than one `#hash` lookup on all of those
elements within an array, and in addition we avoid the cost of
initializing an array on every lookup.
Closes #244 
=> Use nested hashes for multiple required arguments

README.md
Link to https://rubydoc.info/gems/memo_wise (the Gem link), as this
seems to be auto-regenerated when we upload new gem versions, but the
Github repo link appears to be unable to update for many months, even
after manual attempts.
=> Update README.md links to RubyDoc.info

.rubocop.yml, CHANGELOG.md, Gemfile, Gemfile.lock
The `panolint` repo is deprecated; `panolint-ruby` is its replacement.
Closes #308 
=> Switch panolint to panolint-ruby

CHANGELOG.md, README.md, lib/memo_wise/internal_api.rb
In ruby 3.2+, the method `#attached_object` is available to search for object of the singleton class.
It is more simple and faster than using ObjectSpace.
=> Use attached_object in ruby 3.2+.

CHANGELOG.md, README.md
=> Update CHANGELOG.md for v1.8.0

CHANGELOG.md, README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
There is a hack that dynamically defines self.extended when memo_wise is called, but there was a bug that did not consider the case where an existing self.extended existed, so this has been fixed.
=> Fixed a bug that overwrote existing self.extended method definitions.

CHANGELOG.md, README.md, lib/memo_wise.rb, spec/memo_wise_spec.rb
After the #324 PR is merged, I will publish this PR.
=> Fixed a bug that overwrote existing self.inherited method definitions.

.github/workflows/main.yml, CHANGELOG.md, Gemfile, Gemfile.lock, README.md
In addition to adding missing gem 'webrick':
- Switch to BUNDLE_WITH from BUNDLE_WITHOUT
- Enhance some documentation
=> Fix yard server reload

.github/workflows/main.yml, CHANGELOG.md, Gemfile.lock, README.md, lib/memo_wise/version.rb, memo_wise.gemspec
=> rm Ruby 2.4 support to address rexml CVE

Gemfile.lock
=> IOPZ-2913 Address Security Vulnerability with rexml gem

CHANGELOG.md, memo_wise.gemspec
Hello,
please check if this makes sense and if the production gem should also include other files
---
Include only files that are needed for the production gem.
Also avoids to use git to allow to build the package in an environment
that does not have git (on purpose).
173K
```
.dokaz
.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/workflows/dependency-review.yml
.github/workflows/main.yml
.gitignore
.rspec
.rubocop.yml
.ruby-version
.yardopts
CHANGELOG.md
CODE_OF_CONDUCT.md
Gemfile
Gemfile.lock
LICENSE.txt
README.md
Rakefile
benchmarks/Gemfile
benchmarks/benchmarks.rb
bin/console
bin/setup
lib/memo_wise.rb
lib/memo_wise/internal_api.rb
lib/memo_wise/version.rb
logo/logo.png
memo_wise.gemspec
```
19K
```
CHANGELOG.md
LICENSE.txt
README.md
lib/memo_wise.rb …
```
=> Reduce production gem size

CHANGELOG.md, Gemfile.lock, lib/memo_wise/version.rb
=> Version 1.10.0

CHANGELOG.md
=> Update compressed gem size based on rubygems.org stats

CHANGELOG.md, lib/memo_wise.rb
As a side note, this change has been approved here by `@deivid-rodriguez` which is familiar with this issue: https://github.com/activeadmin/arbre/pull/622
---
`require_relative` is preferred over `require` for files within the same
project because it uses paths relative to the current file, making code
more portable and less dependent on the load path.
This change updates internal requires to use `require_relative` for
consistency, performance, and improved portability.
Ref:
- https://github.com/ruby/psych/pull/522
- https://github.com/ruby/logger/pull/20
- https://github.com/ruby/rdoc/pull/658
- https://github.com/panorama-ed/memo_wise/issues/349
- https://github.com/rubocop/rubocop/issues/8748
---
=> Prefer require_relative for internal requires

CHANGELOG.md, Gemfile.lock
This commit bumps the `webrick` dependency to resolve CVE-2024-47220. This vulnerability is not a risk for `memo_wise` users because `webrick` is only used for development of this gem, but it's simple to update so we're doing so.
=> Bump webrick to resolve security vulnerability alert

.github/workflows/main.yml
This commit adds documentation to the fix needed to ensure that Codecov works for PRs that are both created by engineers and created by Dependabot.
---
I tested this by recreating [this Dependabot PR](https://github.com/panorama-ed/memo_wise/pull/363) after setting the secret in the repo settings and confirming that the Codecov CI step passed when previously it failed.
=> Document duplicated `CODECOV_TOKEN` in GitHub settings

benchmarks/benchmarks.rb, memo_wise.gemspec
This commit updates `memo_wise.gemspec` to undefine the `MemoWise::VERSION` constant after it is read, as first suggested in
https://github.com/simplecov-ruby/simplecov/issues/557#issuecomment-825171399.
Before this change, accessing `MemoWise::VERSION` immediately after the `doff_and_don` call in `benchmarks.rb` gives the version of the gem pulled from GitHub, even though `doff_and_don` should mean nothing is in the `MemoWise` namespace. After this change, accessing `MemoWise::VERSION` there gives this error as we expect:
```
uninitialized constant MemoWise (NameError)
```
=> Undefine VERSION in gemspec to avoid namespace pollution between multiple MemoWises

CHANGELOG.md, README.md, benchmarks/Gemfile, benchmarks/benchmarks.rb
This commit adds `short_circu_it` to our benchmarks, and removes unused
code related to benchmarking on Ruby 2.x has been removed.
While working on this commit, many other additional memoization gems
were explored, but all the others I found either did not memoize at the
method level, did not support method arguments (including keyword
arguments), did not correctly memoize values based on method arguments,
or did not run on the latest Ruby version.
=> Add `short_circu_it` to benchmarks and remove unused benchmarking code

CHANGELOG.md, Gemfile.lock, README.md, lib/memo_wise/version.rb
This commit also slightly tweaks the release instructions in `README.md` to reflect the steps I've been following for releasing new gem versions.
=> Bump version to v1.13.0
